services:
  frontend:
    build: ./client
    image: ghcr.io/ivy-christopher/portfolio-client:latest
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - backend
  backend:
    build: ./server
    image: ghcr.io/ivy-christopher/portfolio-server:latest
    environment:
      MONGO_DB: ${MONGO_DB}
      PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge
