services:
  mongodb:
    image: mongo:8.0-noble
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/

      ME_CONFIG_BASICAUTH_PASSWORD: WebUser
      ME_CONFIG_BASICAUTH_USERNAME: WebPass
    depends_on:
      - mongodb
    networks:
      - backend

  frontend:
    build: ./client
    image: ghcr.io/ivy-christopher/portfolio-client:latest
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - backend

  backend:
    build: ./server
    image: ghcr.io/ivy-christopher/portfolio-server:latest
    environment:
      MONGO_DB: mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/mydatabase?authSource=admin
      PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - backend
    depends_on:
      - mongodb

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge
