name: Build and push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Docker Image
        run: docker build -t ghcr.io/IVY-CHRISTOPHER/portfolio-site:latest .

      - name: Push Docker Image
        run: docker push ghcr.io/IVY-CHRISTOPHER/portfolio-site:latest