name: Build and push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Compose Images
        run: |
          docker compose -f compose.yaml build
          docker compose -f compose.yaml push
        env:
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASS: ${{ secrets.MONGO_PASS }}
          FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
          BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
